/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Datos.ConfigTags;
import Datos.Logs;
import Datos.WriteXml;
import Datos.XmlRead;
import com.opencsv.CSVWriter;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;


/**
 *
 * @author ocamp
 */
public class SettingsTags extends javax.swing.JFrame {
    XmlRead XR ;
    public Panel p;
    List<String[]> list;
    public ArrayList<String> codesNames;
    public ArrayList<JTextField> textfieldsNames;
    public ArrayList<JTextField> textfieldsCommands;
    JFileChooser chooser;
    String choosertitle;
    /**
     * Creates new form SettingsTags
     */
    public SettingsTags(Panel p) {
        initComponents();
        this.p = p;
         this.setResizable(false);
       //this.setSize(new Dimension(1366,766));
       this.setLocationRelativeTo(null);
       this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       textfieldsNames = new ArrayList<>(Arrays.asList(jTextField1,jTextField2,jTextField3,jTextField4,jTextField5,jTextField6,jTextField7,jTextField8));
       textfieldsCommands = new ArrayList<>(Arrays.asList(jTextField26,jTextField27,jTextField28,jTextField29,jTextField30,jTextField31,jTextField32,jTextField33));
       XR = new XmlRead();
       codesNames = new ArrayList<>(Arrays.asList("","","",""));
       ConfigTags ct = XR.ReadTagsConfig();
       if (ct.getNames().size() > 0)
       {
        for(int i=0;i<textfieldsNames.size();i++){
            textfieldsNames.get(i).setText(ct.getNames().get(i));
        }
       }     
       if (ct.getCommands().size() > 0)
       {
           
        for(int i=0;i<textfieldsCommands.size();i++){
            if (ct.getCommands().get(i)!=" ")
            {
                textfieldsCommands.get(i).setText(ct.getCommands().get(i));
            }
        }
       }
       if (!" ".equals(ct.ShortcutNew))
       {
           jTextField52.setText(ct.ShortcutNew);
       }
       
       if (!" ".equals(ct.ShortcutCancel))
       {
           jTextField53.setText(ct.ShortcutCancel);
       }
       jComboBox1.setSelectedItem(ct.Color1);
       jComboBox2.setSelectedItem(ct.Color2);
       jComboBox3.setSelectedItem(ct.Color3);
       jComboBox4.setSelectedItem(ct.Color4);
       jComboBox5.setSelectedItem(ct.Color5);
       jComboBox6.setSelectedItem(ct.Color6);
       jComboBox7.setSelectedItem(ct.Color7);
       jComboBox8.setSelectedItem(ct.Color8);
                                                                                    
                                                                                               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField53 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(1039, 409));
        setResizable(false);
        setSize(new java.awt.Dimension(1039, 409));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Comment 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 9, 73, -1));

        jLabel2.setText("Comment 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 73, -1));

        jLabel3.setText("Comment 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 73, -1));

        jLabel4.setText("Comment 4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 73, -1));

        jLabel5.setText("Comment 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 73, -1));

        jLabel6.setText("Comment 6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 73, -1));

        jLabel7.setText("Comment 7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 73, -1));

        jLabel8.setText("Comment 8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 73, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 472, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 472, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 472, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 472, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 472, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 472, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 472, -1));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 472, -1));

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        jTextField26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField26KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 99, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Shortcut");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 73, -1));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Shortcut");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 73, -1));

        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        jTextField27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField27KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 99, -1));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Shortcut");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 73, -1));

        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        jTextField28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField28KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 99, -1));

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Shortcut");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 73, -1));

        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        jTextField29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField29KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 99, -1));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Shortcut");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 73, -1));

        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        jTextField30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField30KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 99, -1));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Shortcut");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 73, -1));

        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        jTextField31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField31KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 99, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Shortcut");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 73, -1));

        jTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField32ActionPerformed(evt);
            }
        });
        jTextField32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField32KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 99, -1));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Shortcut");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 73, -1));

        jTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField33ActionPerformed(evt);
            }
        });
        jTextField33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField33KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 99, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 127, 35));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 127, 35));

        jButton3.setBackground(new java.awt.Color(0, 102, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Nuevo");
        jButton3.setActionCommand("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 127, 35));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setText("Abrir");
        jButton4.setActionCommand("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 127, 35));

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Shortcut Cancelar");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 119, -1));

        jTextField52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField52ActionPerformed(evt);
            }
        });
        jTextField52.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField52KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 119, -1));

        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("Shortcut Añadir");
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(892, 19, 117, -1));

        jTextField53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField53ActionPerformed(evt);
            }
        });
        jTextField53.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField53KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 119, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyan", "None", "Red", "Green", "Blue", "Magenta", "Yellow", "Black", "White", "Default" }));
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        System.out.println("keyCode" + evt.getKeyChar()+ "control"+evt.isControlDown()+ "alt"+evt.isAltDown()+ "shift"+ evt.isShiftDown()+evt.isActionKey());
  // Ctrl + Shift + S
 
  if(evt.getKeyCode() == 83 && evt.isShiftDown() && evt.isControlDown()){
    System.out.println("Save As...");
  }
  // Ctrl + Alt + J
  if(evt.getKeyCode() == 74 && evt.isAltDown() && evt.isControlDown()){
    System.out.println("Step Out");
  }
        
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField26KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField26KeyReleased
        // TODO add your handling code here:
        JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField26KeyReleased

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField27KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField27KeyReleased
        // TODO add your handling code here:
                JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField27KeyReleased

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField28KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField28KeyReleased
        // TODO add your handling code here:
            System.out.println(evt.getKeyCode());
        Field[] fields = java.awt.event.KeyEvent.class.getDeclaredFields();
        System.out.println(evt.getSource());
        JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField28KeyReleased

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField29KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField29KeyReleased
        // TODO add your handling code here:
                JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField29KeyReleased

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField30ActionPerformed

    private void jTextField30KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField30KeyReleased
        // TODO add your handling code here:
                JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField30KeyReleased

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField31ActionPerformed

    private void jTextField31KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField31KeyReleased
        // TODO add your handling code here:
                JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField31KeyReleased

    private void jTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField32ActionPerformed

    private void jTextField32KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField32KeyReleased
        // TODO add your handling code here:
                JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField32KeyReleased

    private void jTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField33ActionPerformed

    private void jTextField33KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField33KeyReleased
        // TODO add your handling code here:
                JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField33KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        ArrayList<String> names = new ArrayList<String>();
        ArrayList<String> commands = new ArrayList<String>();
        
        for(int i=0;i<textfieldsNames.size();i++){
            names.add(textfieldsNames.get(i).getText());
        }
        
        for(int i=0;i<textfieldsCommands.size();i++){
            if (textfieldsCommands.get(i).getText() == "")
            {
                commands.add(" ");
            }
            else
            {
                commands.add(textfieldsCommands.get(i).getText());
            }
        }
        
        ConfigTags ct = new ConfigTags();
        ct.setNames(names);
        ct.setCommands(commands);
        ct.url = p.URL;
        ct.nameFiles = p.fileName;
        if (jTextField52.getText() == "")
            {
                ct.ShortcutNew = " ";
            }
            else
            {
                ct.ShortcutNew = jTextField52.getText();
            }
        if (jTextField53.getText() == "")
            {
                ct.ShortcutCancel = " ";
            }
            else
            {
                ct.ShortcutCancel = jTextField53.getText();
            }
       
        ct.Color3 = jComboBox3.getSelectedItem().toString();
        ct.Color1 = jComboBox1.getSelectedItem().toString();           
        ct.Color2 = jComboBox2.getSelectedItem().toString();
        ct.Color4 = jComboBox4.getSelectedItem().toString();
        ct.Color5 = jComboBox5.getSelectedItem().toString();
        ct.Color6 = jComboBox6.getSelectedItem().toString();
        ct.Color7 = jComboBox7.getSelectedItem().toString();
        ct.Color8 = jComboBox8.getSelectedItem().toString();

        WriteXml xw = new WriteXml();
        try
        {
            xw.WriteTagsConfig(ct);
            p.ResetSettings();
            JOptionPane.showMessageDialog(null, "Configuracion guardada exitosamente");
            this.dispose();
        }
       catch(Exception e){
            System.out.println("Error en escritura de archivo de configuracion "+e);
            JOptionPane.showMessageDialog(null, "Error de configuracion");
            Logs.Write("Error en escritura de archivo de configuracion");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> names = new ArrayList<String>();
        ArrayList<String> commands = new ArrayList<String>();
        
         for(int i=0;i<textfieldsNames.size();i++){
            names.add(textfieldsNames.get(i).getText());
        }
        
        for(int i=0;i<textfieldsCommands.size();i++){
            if (textfieldsCommands.get(i).getText() == "")
            {
                commands.add(" ");
            }
            else
            {
                commands.add(textfieldsCommands.get(i).getText());
            }
        }
        
        ConfigTags ct = new ConfigTags();
        ct.setNames(names);
        ct.setCommands(commands);
        chooser = new JFileChooser(); 
              chooser.setDialogTitle(choosertitle);
    chooser.setCurrentDirectory(new java.io.File(".")); 
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);  
        ct.url = " ";
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
      System.out.println("getCurrentDirectory(): " 
         +  chooser.getCurrentDirectory());
      System.out.println("getSelectedFile() : " 
         +  chooser.getSelectedFile());
      ct.url = chooser.getSelectedFile().toString();
        }
        String resp = "Ingrese el nombre del proyecto";
        boolean auxb = false;
        String auxn= "";
             while (!auxb)
             {
                       String input = JOptionPane.showInputDialog(null, resp);               
            if(input == null || (input != null && ("".equals(input))))   
            {
                auxb = false;
                JOptionPane.showMessageDialog(null, "Ingrese un nombre!");
            }
            else
            {
                auxb = true;
                auxn = input;
            }
             }
        WriteXml xw = new WriteXml();
        try
        {
            if (!ct.url.contains(" "))
            {
                 String[] header = {"markIn", "markOut", "take","comment"};
            list = new ArrayList<>();
            list.add(header);
            
                try (CSVWriter writer = new CSVWriter(new FileWriter(ct.url+"\\"+auxn+".csv"))) {
                writer.writeAll(list);
                ct.nameFiles = auxn;
            }   catch (IOException ex) {
                Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            xw.WriteTagsConfig(ct);
            p.ResetFolderFile(ct.url,ct.nameFiles);
            JOptionPane.showMessageDialog(null, "Configuracion guardada exitosamente");
            this.dispose();
        }
       catch(Exception e){
            System.out.println("Error en escritura de archivo de configuracion "+e);
            JOptionPane.showMessageDialog(null, "Error de configuracion");
            Logs.Write("Error en escritura de archivo de configuracion");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> names = new ArrayList<String>();
        ArrayList<String> commands = new ArrayList<String>();
        
         for(int i=0;i<textfieldsNames.size();i++){
            names.add(textfieldsNames.get(i).getText());
        }
        
        for(int i=0;i<textfieldsCommands.size();i++){
            if (textfieldsCommands.get(i).getText() == "")
            {
                commands.add(" ");
            }
            else
            {
                commands.add(textfieldsCommands.get(i).getText());
            }
        }
        
        ConfigTags ct = new ConfigTags();
        ct.setNames(names);
        ct.setCommands(commands);
        chooser = new JFileChooser(); 
              chooser.setDialogTitle(choosertitle);
    FileNameExtensionFilter filter = new FileNameExtensionFilter("csv", "CSV");
        chooser.addChoosableFileFilter(filter);
        ct.url = " ";
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { 
      System.out.println("getCurrentDirectory(): " 
         +  chooser.getCurrentDirectory());
      System.out.println("getSelectedFile() : " 
         +  chooser.getSelectedFile());
      ct.url = chooser.getCurrentDirectory().toString();
        }
        
        String[] splitted = chooser.getSelectedFile().toString().split( Pattern.quote("\\"));
        
        if (splitted.length > 0)
        {
            
            String name = splitted[splitted.length - 1];
            String auxx = name.substring(0, name.length()-4);
            System.out.println(name + " " + auxx);
             WriteXml xw = new WriteXml();
        try
        {
            
            xw.WriteTagsConfig(ct);
            p.SetNewProject(ct.url,auxx);
            this.dispose();
        }
       catch(Exception e){
            System.out.println("Error en escritura de archivo de configuracion "+e);
            JOptionPane.showMessageDialog(null, "Error de configuracion");
            Logs.Write("Error en escritura de archivo de configuracion");
        }
        }
        /**
       
        */
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField52ActionPerformed

    private void jTextField52KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField52KeyReleased
        // TODO add your handling code here:
                     JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();
    System.out.println(evt.getKeyCode());
    if (evt.getKeyCode()!=8 && evt.getKeyCode() != 10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField52KeyReleased

    private void jTextField53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField53ActionPerformed

    private void jTextField53KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField53KeyReleased
        // TODO add your handling code here:
                     JTextField jf1;
if (evt.getSource() instanceof JTextField) {
    jf1 = (JTextField) evt.getSource();

    if (evt.getKeyCode()!=8 && evt.getKeyCode()!=10)
    {
        if ((evt.getKeyCode()>61 && evt.getKeyCode()<91)||(evt.getKeyCode()>47 && evt.getKeyCode()<59))
        {
            String aux = (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())).substring(0, 0);
            jf1.setText(jf1.getText()+aux);
        }
        else if (evt.getKeyCode()== 17)
        {
            jf1.setText(jf1.getText() + "control" + " ");
        }
        else if (evt.getKeyCode()== 16)
        {
            jf1.setText(jf1.getText() + "shift" + " ");
        }
        else
        {
            jf1.setText(jf1.getText() + (java.awt.event.KeyEvent.getKeyText(evt.getKeyCode())));
        }
    }   
    else
    {
        jf1.setText("");
    }
}
    }//GEN-LAST:event_jTextField53KeyReleased

    
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
